# Generated by Django 4.2.3 on 2023-07-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employee_is_approved_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('verified', models.BooleanField(default=False)),
                ('followers', models.IntegerField(default=0)),
                ('following', models.IntegerField(default=0)),
                ('biography', models.TextField(blank=True, null=True)),
                ('post_urls', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
