# Generated by Django 4.2.3 on 2023-07-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_instagrampost'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubredditData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subreddit_name', models.CharField(max_length=100)),
                ('selftext', models.TextField()),
                ('author_fullname', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('upvote_ratio', models.FloatField()),
                ('score', models.IntegerField()),
                ('author', models.CharField(max_length=100)),
                ('subreddit_subscribers', models.IntegerField()),
            ],
        ),
    ]
