# Generated by Django 4.2.3 on 2023-07-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_subredditdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
