# Generated by Django 4.2.3 on 2023-07-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('new', 'New Lead'), ('engaged', 'Engaged Lead'), ('qualified', 'Qualified Lead'), ('converted', 'Converted Lead'), ('lost', 'Lost Lead')], default='new', max_length=20)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
