# Generated by Django 4.2.3 on 2023-07-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('full_text', models.TextField()),
                ('user_name', models.CharField(max_length=255)),
                ('screen_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('followers_count', models.IntegerField()),
                ('friends_count', models.IntegerField()),
                ('lang', models.CharField(max_length=10)),
            ],
        ),
    ]
