# Generated by Django 4.2.3 on 2023-07-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='created_at',
            field=models.CharField(max_length=255),
        ),
    ]
