# Generated by Django 4.2.3 on 2023-07-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_facebookpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=255)),
                ('post_content', models.TextField()),
                ('keyword', models.CharField(max_length=50)),
            ],
        ),
    ]
