# Generated by Django 4.2.3 on 2023-07-18 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_employee_user'),
        ('leads', '0006_remove_lead_email_remove_lead_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='handled_by',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.employee'),
        ),
    ]
