# Generated by Django 4.2.3 on 2023-07-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_employee_user'),
        ('leads', '0007_alter_lead_handled_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='handled_by',
        ),
        migrations.AddField(
            model_name='lead',
            name='handled_by',
            field=models.ManyToManyField(default=None, null=True, to='accounts.employee'),
        ),
    ]
